#!/usr/bin/env python3

"""a simple test of the interpolator
"""
__author__ = "Reed Essick (reed.essick@gmail.com)"

#-------------------------------------------------

import numpy as np

import matplotlib
matplotlib.use("Agg")
from matplotlib import pyplot as plt

from argparse import ArgumentParser

### non-standard libraries
import mgpi

#-------------------------------------------------

# let's build an interpolator over the speed of sound using half the points available
# the speed of sound seems to have the most interesting behavior, or at least features
# that might be the hardest for the GP to emulate accruately

path = '../etc/equation_of_state.csv.gz'
print('loading data from : '+path)

# load sample data
data = np.genfromtxt(path, delimiter=',', names=True)

# grab the relevant data
baryon_chemical_potential = data['muB_MeV']
temperature = data['T_MeV']
speed_of_sound = data['speed_of_sound']

num = len(np.unique(baryon_chemical_potential))
shape = (len(data)//num, num)

print('    found data with shape :', shape)

baryon_chemical_potential = baryon_chemical_potential.reshape(shape)
temperature = temperature.reshape(shape)
speed_of_sound = speed_of_sound.reshape(shape)

# now decimate the data so that the covariance matrices we build fit in memory
downsample = 10

baryon_chemical_potential = baryon_chemical_potential[::downsample, ::downsample]
temperature = temperature[::downsample, ::downsample]
speed_of_sound = speed_of_sound[::downsample, ::downsample]

print('    downselected data to shape :', np.shape(speed_of_sound))

#------------------------

# let's then divide this into training and testing sets
# we divid the grid in the following way: (o --> training set, x --> test set)
#     o o o o o
#     o x o x o
#     o o o o o
#     o x o x o
#     o o o o o

print('formatting training and test sets')

source_x = []
source_f = []
target_x = []
target_f = []

for ind in range(len(speed_of_sound)):
    offset = ind % 2 ### figure out whether this is an odd or an even row

    if offset: # an odd row, so only take every other sample for training set
        # grab the training data
        source_x.append(np.transpose([baryon_chemical_potential[ind, ::2], temperature[ind, ::2]]))
        source_f.append(speed_of_sound[ind, ::2])

        # grab the test data
        target_x.append(np.transpose([baryon_chemical_potential[ind, 1::2], temperature[ind, 1::2]]))
        target_f.append(speed_of_sound[ind,1::2])

    else: # an even row, so grab everything
        # grab the training data
        source_x.append(np.transpose([baryon_chemical_potential[ind,:], temperature[ind,:]]))
        source_f.append(speed_of_sound[ind,:])

source_x = np.concatenate(tuple(source_x))
source_f = np.concatenate(tuple(source_f))

target_x = np.concatenate(tuple(target_x))
target_f = np.concatenate(tuple(target_f))

print('    selected:\n        %d training points\n        %d test points'%(len(source_x), len(target_x)))

#------------------------

print('estimating appropriate hyperparameters and constructing kernel')

# now, let's guess at appropriate hyperparameters
ave = np.mean(source_f)       ### mean of the process

### FIXME! pick these based on maximizing the marginal likelihood for (source_f, source_x)

sigma = np.std(source_f) * 2  ### variance based on spread of the function

lengths = [                   ### based on the average grid spacing
    2 * np.mean(np.diff(baryon_chemical_potential[0,:])),
    2 * np.mean(np.diff(temperature[:,0])),
]

# construct a kernel
kernel = mgpi.CombinedKernel(
    mgpi.SquaredExponentialKernel(sigma, *lengths),
    mgpi.WhiteNoiseKernel(sigma/1000), # a small white noise component for numerical stability
)

#------------------------

print('computing interpolation estimate')

# now let's compute estimates of the speed of sound at the test points
mean, cov = mgpi.condition(target_x, source_x, source_f - ave, kernel, verbose=True)
mean += ave ### add back in the mean that I substracted

#------------------------

# make some plots of the predicted mean and covariance
# in particular, compare this to the true function : target_f = f(target_x)

#-----------

print('histogram the errors in the interpolator')

fig = plt.figure(figsize=(8,4))

nbins = int(len(target_f)**0.5)

# absolute error
ax = plt.subplot(1,2,1)
ax.hist(mean-target_f, bins=nbins, histtype='step', log=True)
ax.set_xlabel('$E[f(x)] - f(x)$')
ax.tick_params(
    left=True,
    right=True,
    top=True,
    bottom=True,
    which='both',
    direction='in',
)

# scaled error
ax = plt.subplot(1,2,2)
ax.hist((mean-target_f)/np.diag(cov)**0.5, bins=nbins, histtype='step', log=True)
ax.set_xlabel('$(E[f(x)] - f(x)]/\sigma_{f(x)}$')
ax.tick_params(
    left=True,
    right=True,
    top=True,
    bottom=True,
    which='both',
    direction='in',
)

# save
plt.subplots_adjust(
    left=0.10,
    bottom=0.15,
    top=0.98,
    right=0.95,
    wspace=0.15,
)

path = 'error-histograms.png'
print('    saving : '+path)
fig.savefig(path)
plt.close(fig)

#-----------

# plot the distribution of errors across the function's domain

# first, reshape the target data into something I can use
target_bcp, target_tmp = np.transpose(target_x)

num = len(np.unique(target_bcp))
shape = (len(target_bcp)//num, num)

target_bcp = target_bcp.reshape(shape)[0,:]
target_tmp = target_tmp.reshape(shape)[:,0]
target_f = target_f.reshape(shape)
mean = mean.reshape(shape)
stdv = (np.diag(cov)**0.5).reshape(shape)

vmin = np.min([mean, target_f])
vmax = np.max([mean, target_f])

# now make some plots

fig = plt.figure(figsize=(8,6))

# true function
ax = plt.subplot(2,3,1)
mappable = ax.imshow(
    target_f,
    extent=[np.min(target_bcp), np.max(target_bcp), np.min(target_tmp), np.max(target_tmp)],
    vmin=vmin,
    vmax=vmax,
    aspect='auto',
    origin='lower',
)
plt.setp(ax.get_xticklabels(), visible=False)
ax.set_ylabel('$T\,[\mathrm{MeV}]$')
ax.set_title('$f(x)$')
ax.tick_params(
    left=True,
    right=True,
    top=True,
    bottom=True,
    which='both',
    direction='in',
)

cb = plt.colorbar(mappable)

# mean
ax = plt.subplot(2,3,2)
mappable = ax.imshow(
    mean,
    extent=[np.min(target_bcp), np.max(target_bcp), np.min(target_tmp), np.max(target_tmp)],
    vmin=vmin,
    vmax=vmax,
    aspect='auto',
    origin='lower',
)
plt.setp(ax.get_xticklabels(), visible=False)
plt.setp(ax.get_yticklabels(), visible=False)
ax.set_title('$E[f(x)]$')
ax.tick_params(
    left=True,
    right=True,
    top=True,
    bottom=True,
    which='both',
    direction='in',
)

cb = plt.colorbar(mappable)

# uncertainty
ax = plt.subplot(2,3,3)
mappable = ax.imshow(
    stdv,
    extent=[np.min(target_bcp), np.max(target_bcp), np.min(target_tmp), np.max(target_tmp)],
    aspect='auto',
    origin='lower',
)
plt.setp(ax.get_xticklabels(), visible=False)
plt.setp(ax.get_yticklabels(), visible=False)
ax.set_title('$\sigma_{f(x)}$')
ax.tick_params(
    left=True,
    right=True,
    top=True,
    bottom=True,
    which='both',
    direction='in',
)

cb = plt.colorbar(mappable)

# absolute error
ax = plt.subplot(2,2,3)
mappable = ax.imshow(
    mean - target_f,
    extent=[np.min(target_bcp), np.max(target_bcp), np.min(target_tmp), np.max(target_tmp)],
    aspect='auto',
    origin='lower',
)
ax.set_xlabel('$\mu_B\,[\mathrm{MeV}]$')
ax.set_ylabel('$T\,[\mathrm{MeV}]$')
ax.set_title('$E[f(x)] - f(x)$')
ax.tick_params(
    left=True,
    right=True,
    top=True,
    bottom=True,
    which='both',
    direction='in',
)

cb = plt.colorbar(mappable)

# scaled error
ax = plt.subplot(2,2,4)
mappable = ax.imshow(
    (mean - target_f) / stdv,
    extent=[np.min(target_bcp), np.max(target_bcp), np.min(target_tmp), np.max(target_tmp)],
    aspect='auto',
    origin='lower',
)
ax.set_xlabel('$\mu_B\,[\mathrm{MeV}]$')
plt.setp(ax.get_yticklabels(), visible=False)
ax.set_title('$(E[f(x)] - f(x))/\sigma_{f(x)}$')
ax.tick_params(
    left=True,
    right=True,
    top=True,
    bottom=True,
    which='both',
    direction='in',
)

cb = plt.colorbar(mappable)

# save
plt.subplots_adjust(
    left=0.10,
    bottom=0.10,
    top=0.90,
    right=0.95,
    hspace=0.15,
    wspace=0.20,
)

path = 'error-surface.png'
print('    saving : '+path)
fig.savefig(path)
plt.close(fig)
