#!/bin/bash

# a quick script to iterate over commands and produce regridded data at different resolutions
# Reed Essick (reed.essick@gmail.com)

#-------------------------------------------------

declare -A PATHS

#PATHS[LS180]="LS180_234r_136t_50y_analmu_20091212_SVNr26.h5"
PATHS[LS220]="LS220_234r_136t_50y_analmu_20091212_SVNr26.h5"
PATHS[LS375]="LS375_234r_136t_50y_analmu_20091212_SVNr26.h5"

PATHS[Hempel_rho222]="Hempel_SFHoEOS_rho222_temp180_ye60_version_1.1_20120817.h5"
PATHS[Hempel_rho234]="Hempel_SFHxEOS_rho234_temp180_ye60_version_1.1_20120817.h5"

#-------------------------------------------------

for NAME in ${!PATHS[@]}
do 

    # fixed step sizes

#    for NUM in 50 100 200 300 400 500
    for NUM in 500
    do

#        echo \
        ./regrid \
            ${PATHS[$NAME]} \
            regrid-${NAME}_${NUM}logenergy.hdf \
            --grid ${NUM} 17.5 33.0 \
            --verbose \
            --plot

        echo \
        ./regrid2 \
            ${PATHS[$NAME]} \
            regrid2-${NAME}_${NUM}logenergy.hdf \
            --grid ${NUM} 16.0 17.5 33.0 \
            --verbose \
            --plot

    done

    #------------------------

    # addaptive step sizes

    echo \
    ./regrid3 \
        ${PATHS[$NAME]} \
        regrid2-${NAME}_${NUM}logenergy.hdf \
        --min-num-grid 2 \
        --rtol 1e-2 \
        --num-cdf-grid 100000 \
        --min-low-loge-step 1e-2 \
        --min-high-loge-step 1e-1 \
        --verbose \
        --plot

done
