#!/bin/bash

# grab EoS tables that are too big to store within git
# EoS are available here: https://stellarcollapse.org/equationofstate.html
# Reed Essick (reed.essick@gmail.com)

#-------------------------------------------------

### download individual EoS tables

# Lattimer and Swesty

wget https://stellarcollapse.org/EOS/LS180_234r_136t_50y_analmu_20091212_SVNr26.h5.bz2
#wget https://stellarcollapse.org/EOS/LS220_234r_136t_50y_analmu_20091212_SVNr26.h5.bz2
#wget https://stellarcollapse.org/EOS/LS375_234r_136t_50y_analmu_20091212_SVNr26.h5.bz2
#wget https://stellarcollapse.org/~evanoc/LS220_240r_140t_50y_analmu_20120628_SVNr28.h5.bz2

#------------------------

# H. Shen

#wget https://stellarcollapse.org/~evanoc/HShenEOS_rho220_temp180_ye65_version_1.1_20120817.h5.bz2
#wget https://stellarcollapse.org/~evanoc/HShen_HyperonEOS_rho220_temp180_ye65_version_1.1_20131007.h5.bz2

#------------------------

# G. Shen

#wget https://stellarcollapse.org/~evanoc/GShen_NL3EOS_rho280_temp180_ye52_version_1.1_20120817.h5.bz2
#wget https://stellarcollapse.org/~evanoc/GShenFSU_1.7EOS_rho280_temp180_ye52_version_1.1_20120817.h5.bz2
#wget https://stellarcollapse.org/~evanoc/GShenFSU_2.1EOS_rho280_temp180_ye52_version_1.1_20120824.h5.bz2

#------------------------

# Hempel

#wget https://stellarcollapse.org/~evanoc/Hempel_TMAEOS_rho234_temp180_ye60_version_1.1_20120817.h5.bz2
#wget https://stellarcollapse.org/~evanoc/Hempel_TM1EOS_rho234_temp180_ye60_version_1.1_20120817.h5.bz2
#wget https://stellarcollapse.org/~evanoc/Hempel_FSGEOS_rho234_temp180_ye60_version_1.1_20120817.h5.bz2
#wget https://stellarcollapse.org/~evanoc/Hempel_NL3EOS_rho234_temp180_ye60_version_1.1_20120817.h5.bz2
#wget https://stellarcollapse.org/~evanoc/Hempel_DD2EOS_rho234_temp180_ye60_version_1.1_20120817.h5.bz2
#wget https://stellarcollapse.org/~evanoc/Hempel_IUFEOS_rho234_temp180_ye60_version_1.1_20140129.h5.bz2

#------------------------

# Steiner

#wget https://stellarcollapse.org/~evanoc/Hempel_SFHoEOS_rho222_temp180_ye60_version_1.1_20120817.h5.bz2
#wget https://stellarcollapse.org/~evanoc/Hempel_SFHxEOS_rho234_temp180_ye60_version_1.1_20120817.h5.bz2

#------------------------

# Banik

#wget https://stellarcollapse.org/~evanoc/BHB_lEOS_rho234_temp180_ye60_version_1.02_20140422.h5.bz2
#wget https://stellarcollapse.org/~evanoc/BHB_lpEOS_rho234_temp180_ye60_version_1.02_20140422.h5.bz2

#-------------------------------------------------

### decompress them

for compressed in $(ls ./*bz2)
do
    bzip2 -d $compressed
done
